version: '3.8'
services:
  fastlio2:
    network_mode: "host"          
    container_name: fastlio2
    runtime: nvidia
    user: calib
    ipc: host
    tty: true
    privileged: true
    working_dir: /workspace/
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - UID=${UID:-1001}
        - GID=${GID:-1001}
        - USERNAME=${USERNAME:-default}
        - PASSWORD=${PASSWORD:-default}
        - BASE_IMAGE=thecanadianroot/opencv-cuda:ubuntu20.04-cuda11.3.1-opencv4.5.2-rosnoetic
    volumes:
      - .:/workspace/src/fastlio2
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ${HOME}/.hxbasic:/home/calib/.hxbasic
      - ${HOME}/.hxbasic:/root/.hxbasic
      # docker volume create -d local --opt type=none --opt o=bind --opt device=$PWD/data auto_calib_data
      - auto_calib_data:/workspace/src/datasets
    devices:
      - /dev/dri:/dev/dri
    environment:
      - UID=${UID:-1000}
      # - DISPLAY=unix$DISPLAY
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY=/tmp/.docker.xauth

volumes:
  auto_calib_data:
    name: auto_calib_data
    external: true